Frontend:
  impl: HBMPIMTrace
  clock_ratio: 8
  path: ../example.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: HBMPIMSystem
  clock_ratio: 3

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_PIM_6Gb
    timing:
      preset: HBM2_PIM_6Gb_timing 

  Controller:
    impl: HBMPIMController
    clock_ratio: 3
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
